name: build
on:
  push:
    tags:
      - '*'
jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install dpkg-dev
      - name: checkout
        uses: actions/checkout@v2
      - name: unshallow
        run: git fetch --prune --unshallow
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: build
        run: make all -e VERSION=${{ env.RELEASE_VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/zram-swap-${{ env.RELEASE_VERSION }}.deb