name: build
on:
  push:
    tags:
      - '*'
jobs:
  build-deb:
    runs-on: cmd.cat/make/dpkg-deb
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: unshallow
        run: git fetch --prune --unshallow
      - name: build
        run: make all -e VERSION=${{ github.ref }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/zram-swap-${{ github.ref }}.deb