name: build
on:
  push:
    tags:
      - 'v*'
jobs:
  build-deb:
    runs-on: cmd.cat/make/dpkg-deb
    steps:
      - name: checkout
        users: actions/checkout@v2
      - name: unshallow
        run: git fetch --prune --unshallow
      - name: build
        run: make all
