name: build
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install dpkg-dev
      - name: checkout
        uses: actions/checkout@v2
      - name: unshallow
        run: git fetch --prune --unshallow
      - name: Set env from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        if: startsWith(github.ref, '/refs/heads/') == false
      - name: Set env from branch
        if: startsWith(github.ref, '/refs/heads/')
        run: echo "RELEASE_VERSION=0-${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: build
        run: sudo make all -e VERSION=${{ env.RELEASE_VERSION }}
      - name: build_deb
        uses: jiro4989/build-deb-action@v2
        with:
          package: zram-swap
          package_root: build/zram-swap-${{ env.RELEASE_VERSION }}
          maintainer: Dmitry Orlov <me@mosquito.su>
          version: ${{ env.RELEASE_VERSION }}
          arch: 'all'
          depends: 'python3, libpython3-stdlib'
          desc: 'Easy way to configure swap over zram'
      - name: release
        if: startsWith(github.ref, '/refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ needs.build_deb.outputs.file_name }}.deb